getoutreach/etl

lib/etl/schema/table.rb
=> add default datetime

lib/etl/output/redshift.rb
Change credentials for loading s3 data into Redshift
[#144641701]
=> change credentials in query

lib/etl/job/base.rb, lib/etl/output/redshift.rb, spec/output/redshift_spec.rb
=> add upload-to-s3 function to redshift output

lib/etl/config.rb, lib/etl/input/influxdb.rb, lib/etl/output/redshift.rb
=> config for influx

lib/etl/core.rb, lib/etl/job/base.rb, lib/etl/job/exec.rb, lib/etl/job/manager.rb, lib/etl/util/logger.rb, lib/etl/util/metrics.rb, spec/util/metrics_spec.rb
Plug it in with a callback setting, since this gem shouldn't depend on
outreach-metrics-agent.
[#145251853]
=> Output metrics for job run

lib/etl/output/redshift.rb
=> fix for reserved words and long session names

lib/etl/output/redshift.rb
=> Count # input rows

lib/etl/input/influxdb.rb
=> delete logging all rows

lib/etl/input/multi_influxdb.rb, lib/etl/query/sequel.rb, spec/query/sequel_spec.rb
=> Add a new query builder and a new class for influx input

lib/etl/input/multi_influxdb.rb
=> Add methods to create data-schema hash

lib/etl/input/multi_influxdb.rb
=> Add parameters for time interval and start date

lib/etl/input/multi_influxdb.rb
[#146536255]
CPU utilization of staging influxdb reached almost 100 % again. Put a parameter for sleep.
=> Add a parameter for sleep process

.gitignore, lib/etl/input/date_table.rb, spec/input/date_table_spec.rb
[#146654783] - Partially completes the workitem. It will add create the
datetimes. Populate will occur in downstream projects
=> Add a DateTime Table input

lib/etl/input/multi_influxdb.rb, spec/input/influxdb_spec.rb, spec/input/multi_influxdb_spec.rb
=> Add influx docker to input influx test

lib/etl/input/multi_influxdb.rb, lib/etl/output/redshift.rb, spec/input/multi_influxdb_spec.rb, spec/output/redshift_spec.rb
=> Ignore influx rows which include nil data

Gemfile.lock, etl.gemspec
=> Add slack to gemspec

.gitignore
=> Add all yml files to gitignore

bin/generate_config_files, circle.yml, etc/core.yml.template, etc/erb_templates/aws.yml.erb, etc/erb_templates/core.yml.erb, etc/erb_templates/database.yml.erb, etc/erb_templates/redshift.yml.erb, lib/etl/config.rb, lib/etl/core.rb, lib/etl/output/sequel.rb, spec/input/influxdb_spec.rb, spec/input/sequel_spec.rb, spec/lib/etl/cli/cmd/job_spec.rb, spec/output/influxdb_spec.rb, spec/output/redshift_spec.rb, spec/output/sequel_spec.rb
=> Set up CircleCI

lib/etl/input/multi_influxdb.rb
=> Add more logs for influx input

lib/etl/input/multi_influxdb.rb, lib/etl/query/sequel.rb, spec/input/multi_influxdb_spec.rb, spec/query/sequel_spec.rb
=> Fix offset of multi-influx

.pre-commit-config.yaml, circle.yml
=> pre-commit

lib/etl/output/redshift.rb, lib/etl/schema/column.rb, lib/etl/schema/table.rb, spec/output/redshift_spec.rb
=>  Primary key in redshift

lib/etl/output/redshift.rb, spec/output/redshift_spec.rb
=> Add schema-method

lib/etl/job/exec.rb, lib/etl/slack/notifier.rb
=> Make slack messages clear

etc/aws.yml.template, lib/etl/input/base.rb, lib/etl/input/multi_influxdb.rb, lib/etl/job/base.rb, lib/etl/job/exec.rb
=> Output timerange of etl jobs to slack

lib/etl/output/redshift.rb, lib/etl/redshift/client.rb, lib/etl/redshift/table.rb, lib/etl/schema/table.rb, spec/output/redshift_spec.rb, spec/redshift/client_spec.rb, spec/redshift/table_spec.rb
1) Created a Redshift table type
2) Moved code that does sql creation into Redshift table
3) Updated Redshift output to use redshift table to create tables
4) Implemented a create table with various capabilities (backup, like,
distkey, sortkeys, and diststyle)
=> Add dist all style and refactor table create

lib/etl/redshift/table.rb, spec/redshift/table_spec.rb
=> Add identity

lib/etl/redshift/client.rb
1) Fix bug where driver is not specified and can't connect
=> Update connection parameter defaults

Gemfile.lock, etl.gemspec, lib/etl/redshift/client.rb, lib/etl/redshift/table.rb, spec/output/redshift_spec.rb, spec/redshift/client_spec.rb
Having problems deploying the odbc driver so for the mean time until
there is a xenial build machine we need to use postgres driver against
redshift
=> Move things back to pg provider

lib/etl/cli/cmd/job.rb, lib/etl/cli/cmd/scheduler.rb, lib/etl/job/base.rb, lib/etl/job/exec.rb, lib/etl/redshift/batch_factory.rb, spec/redshift/batch_factory_spec.rb
- Allows custom creation of batch factories with parameters which is
needed for redshift
- Implement basic redshift batch factory
=> Add batch_factory on Job and one one for redshift

lib/etl/migration/Redshift.rb, lib/etl/output/redshift.rb, spec/input/multi_influxdb_spec.rb, spec/output/redshift_spec.rb
=> add flag for creating new table when it doesnt exist

lib/etl/output/redshift.rb, spec/output/redshift_spec.rb
=> fix 'unknown keywords' bug

lib/etl/cli/cmd/migration.rb, lib/etl/cli/main.rb, lib/etl/job/migratable_base.rb, spec/job/migratable_base_spec.rb, spec/lib/etl/cli/cmd/migration_spec.rb
=> Add functions for migraitons parameters instead of accessor

lib/etl/redshift/table.rb, spec/output/redshift_spec.rb, spec/redshift/table_spec.rb
=> backslash for column names in queries

lib/etl/job/migratable_base.rb
=> update schema deploy version after migration

lib/etl/config.rb, lib/etl/redshift/batch_factory.rb
=> modify the method to get env var for db

lib/etl/cli/cmd/migration.rb, lib/etl/redshift/table.rb
=> modify migration

lib/etl/redshift/batch_factory.rb, lib/etl/redshift/client.rb, spec/redshift/client_spec.rb
=> Add new redshift functions

lib/etl/config.rb, lib/etl/models/job_run_repository.rb
=> Fix dbconfig adapter

lib/etl/models/job_run_repository.rb
=> remove invalid config

lib/etl/output/redshift.rb
=> modify functions in redshift

lib/etl/cli/cmd/job.rb
=> Fix the slack bug

lib/etl/output/redshift.rb, spec/output/redshift_spec.rb
=> fix the error

lib/etl/input/multi_influxdb.rb, lib/etl/redshift/table.rb, lib/etl/schema/table.rb
=> add timestamp

lib/etl/redshift/client.rb, lib/etl/redshift/table.rb, lib/etl/schema/column.rb, lib/etl/schema/table.rb, spec/redshift/client_spec.rb, spec/redshift/table_spec.rb
=> Enable creating foreign keys in redshift

lib/etl/output/redshift2.rb, spec/output/redshift2_spec.rb
=> Add a hook to allow pre transformers hook

lib/etl/output/redshift.rb, lib/etl/output/redshift2.rb, lib/etl/redshift/client.rb, spec/redshift/client_spec.rb, spec/redshift/column_value_augmenter_spec.rb, spec/redshift/date_table_id_augmenter_spec.rb
=> change delimiter

lib/etl/output/redshift2.rb
=> instance variables

lib/etl/redshift/table.rb, spec/lib/etl/cli/cmd/migration_spec.rb, spec/redshift/table_spec.rb
=> fix a bug so that etl jobs work

etc/erb_templates/redshift_migration.erb, lib/etl/cli/cmd/migration.rb, spec/lib/etl/cli/cmd/migration_spec.rb
=> Remove line break

lib/etl/job/base.rb
=> add batch on slack notifier

lib/etl/job/base.rb
=> Exclude empty batch slack message

lib/etl/config.rb, lib/etl/input/sequel.rb, lib/etl/queue/sqs.rb, lib/etl/redshift/client.rb
=> Enable tableschema caching and sequel conn testing

lib/etl/queue/sqs.rb
=> Fix the sqs to string issue copy pasta error

lib/etl/cli/cmd/worker.rb
=> Update work to load user classes

lib/etl/output/redshift.rb, lib/etl/redshift/client.rb, spec/redshift/client_spec.rb
Fixes issues where files are filling up the machine.
[DW-281]
=> Update to delete files that are pushed to s3

lib/etl/queue/sqs.rb
=> Fix errant while loop

lib/etl/config.rb, lib/etl/output/redshift.rb, lib/etl/redshift/client.rb
=> Allow different tmp working dir for redshift

lib/etl/input/sequel.rb
=> close connection when needed

lib/etl/cache/base.rb, lib/etl/job/exec.rb
=> slack host name when a job starts running

lib/etl/cli/command_extension_manager.rb, lib/etl/cli/main.rb
=> Add ability to add command extensions.

lib/etl/schedule/daily_time_schedule.rb, spec/schedule/daily_time_schedule_spec.rb
=> Add a Daily Times schedule in etl

lib/etl/models/job_run_repository.rb, lib/etl/redshift/client.rb, lib/etl/schedule/daily_time_schedule.rb
=> Delete s3 files and add logging for scheduling

lib/etl/job/exec.rb
=> all jobs failed at worker, so put error messgages on slack

lib/etl/redshift/table.rb
=> fix the order to execute dist style

lib/etl/redshift/table.rb, spec/redshift/table_spec.rb
[DW-351]
Fix the bug I made on previous PR
=> use instance variable

lib/etl/output/redshift2.rb, lib/etl/redshift/client.rb, lib/etl/redshift/table.rb, lib/etl/redshift/validator_base.rb
=> add validator class

lib/etl/cache/base.rb, spec/cache/cache_spec.rb
=> modify condition

lib/etl/redshift/client.rb, lib/etl/redshift/table.rb, spec/output/redshift2_spec.rb, spec/output/redshift_spec.rb, spec/redshift/client_spec.rb, spec/redshift/table_spec.rb
=> Change redshift client api's to give schema name

lib/etl/redshift/client.rb
=> rename variable to avoid calling function

lib/etl/job/exec.rb
=> loading error handlilng

lib/etl/redshift/client.rb
[DW-409](https://outreach-io.atlassian.net/browse/DW-409)
=> Fix primary key redshift schema bug

lib/etl/redshift/client.rb, lib/etl/redshift/stl_load_error.rb, spec/redshift/client_spec.rb
=> Add ability get get load errors from redshift

lib/etl/job/exec.rb
=> fix standard error bug

lib/etl/job/exec.rb, lib/etl/job/migratable_base.rb, lib/etl/migration/redshift.rb, spec/job/migratable_base_spec.rb
=> Close client migrate

lib/etl/redshift/client.rb, spec/redshift/client_spec.rb
=> Add functions to use multiple files with copy command

lib/etl/redshift/client.rb
=> Should not insert data if csv create failure

lib/etl/redshift/client.rb
reraised exception that copy_from_s3 raises
also modified stl_load_errors to pull all errors for the copy (multiple files =
multiple errors)
part of [DW-474]
=> Fail jobs when they fail to copy from s3 to redshift

lib/etl/redshift/client.rb
=> delete local files on errors

lib/etl/cli/cmd/job.rb, lib/etl/models/job_run.rb
=> Update etl job run command to take input file

lib/etl/models/job_run_repository.rb
=> Add to job run repos to get latest successful job

lib/etl/queue/base.rb, lib/etl/queue/file.rb, lib/etl/queue/sqs.rb, spec/queue/file_spec.rb
=> Add ability to stop queue from dequeuing

lib/etl/redshift/client.rb, spec/redshift/client_spec.rb
changed temp folder / file name hash to 10 chars instead of 5
made tests properly remove temp local files
[DW-540]
=> made upload to s3 use temp folder each time to avoid dups

lib/etl/redshift/client.rb, spec/redshift/client_spec.rb
=> re-added s3 upload folders and temp file deletion before upload [DW-540]

lib/etl/models/job_run_repository.rb, lib/etl/slack/notifier.rb
added thread locking on slack notifier
[DW-551]
=> added thread locking on job run repository

lib/etl/core.rb, lib/etl/queue/base.rb, lib/etl/queue/rabbitmq.rb, lib/etl/queue/sqs.rb
=> Fix consul dequeuer and rabbitmq parameters

lib/etl/cli/cmd/worker.rb, lib/etl/core.rb
=> Fix queue init

lib/etl/queue/rabbitmq.rb
bunny uses a background thread to handle network i/o (fine)
=> changed bunny to default to multithread

lib/etl/redshift/client.rb, lib/etl/redshift/nil_string_row_transformer.rb, lib/etl/redshift/table.rb, lib/etl/schema/table.rb, spec/redshift/client_spec.rb, spec/redshift/nil_string_row_transformer_spec.rb, spec/schema/table_spec.rb
=> Update to fix empty strings

lib/etl/job/exec.rb, lib/etl/redshift/nil_string_row_transformer.rb, lib/etl/slack/notifier.rb
[DW-556]
Fix nil transformer to handle rows
=> Update slack to ratelimit

lib/etl/redshift/alter_table.rb, spec/redshift/alter_table_spec.rb
=> Enable easier alter tables for migrations

lib/etl/config.rb, spec/config_spec.rb
=> Add ability to get secrets from files

lib/etl/config.rb, lib/etl/queue/rabbitmq.rb, spec/config_spec.rb, spec/job_repository_helper.rb
=> Update to add rabbitmq env vars

lib/etl/s3/bucket_manager.rb, lib/etl/s3/csv_files_uploading_streamer.rb, spec/s3/bucket_manager_spec.rb, spec/s3/csv_files_uploading_streamer_spec.rb
=> Add csv files uploading streamer and tests

Gemfile.lock, etl.gemspec, lib/etl/output/redshift.rb, lib/etl/redshift/client.rb, lib/etl/s3/bucket_manager.rb, lib/etl/s3/csv_files_uploading_streamer.rb, lib/etl/util/tmp_util.rb, spec/redshift/client_spec.rb, spec/s3/bucket_manager_spec.rb
=> Integrate bucketmanager and csv file streamer

lib/etl/models/job_run_repository.rb
=> Update bad var name in postgres backoff

lib/etl/redshift/alter_table.rb
https://outreach-io.atlassian.net/browse/DSC-1703
=> Add copy_column func to AlterTable to copy between columns
